project:
  type: website
  output-dir: docs

website:
  title: "Thu Ngo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: STAT_244-SC.qmd
        text: "STAT 244-SC"

format:
  html:
    respect-user-color-scheme: true
    theme: 
      light: flatly
      dark: darkly
      
    css: styles.css
    toc: true

editor: visual

